{ pkgs, ... }:
{
  home.packages = with pkgs; [
    actionlint
    alacritty
    alsa-utils
    arandr
    bat
    btop
    cabal-install
    cachix
    delta
    dig
    discord-ptb
    docker-compose
    dprint
    emacs
    feh
    firefox
    fzf
    gcc
    ghc
    gimp
    gnumake
    gnupg
    haskell-language-server
    haskellPackages.hasktags
    jq
    libnotify
    nil
    nixpkgs-fmt
    nodePackages.typescript
    nodePackages.typescript-language-server
    olive-editor
    pavucontrol
    python39
    ripgrep
    slack
    tmux
    tree
    tree-sitter
    (vivaldi.override { proprietaryCodecs = true; enableWidevine = false; })
    vlc
    vscode-langservers-extracted
    x265
    xclip
    xdg-utils
  ];
}

